# suppress inspection "UnusedProperty" for whole file
displayName=Partner Slayer
author=Thource
support=https://github.com/Thource/partner-slayer
description=Provides various QoL features to make Mastering Mixology better.
tags=mastering mixology,qol
plugins=dev.thource.runelite.partnerslayer.PartnerSlayerPlugin
